apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: amazon-cloudwatch
  name: cloudwatch-agent-role
rules:
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "list", "watch"]
