apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: efs-sc
provisioner: efs.csi.aws.com
parameters:
  provisioningMode: efs-ap
  fileSystemId: YourEFSFileSystemID  # Ensure this is your EFS file system ID
  directoryPerms: "700"
  basePath: "/prometheus"  # Base path where Access Point starts
