apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ghost-rolebinding
  namespace: default
subjects:
- kind: ServiceAccount
  name: ghost-service-account
  namespace: default
roleRef:
  kind: Role
  name: ghost-role
  apiGroup: rbac.authorization.k8s.io
