apiVersion: v1
kind: ServiceAccount
metadata:
  name: grafana-service-account
  namespace: monitoring
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::247867391235:role/GrafanaRoleForEKS"
