apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: 'kubernetes-apiservers'
        scheme: https  # Assuming your API servers are correctly configured with HTTPS
        tls_config:
          insecure_skip_verify: true
        kubernetes_sd_configs:
          - role: endpoints
        relabel_configs:
          - source_labels: [__meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
            regex: 'kubernetes;https'
            action: keep  # Adjust the regex according to your service names and ports

      - job_name: 'internal-services'
        scheme: http  # No TLS for these
        static_configs:
          - targets: ['10.0.2.92:5432', '10.0.2.175:9153']  # Example: PostgreSQL, Node Exporter
            labels:
              group: 'databases'

      - job_name: 'node-exporters'
        scheme: http
        static_configs:
          - targets: ['10.0.2.191:9100']  # Standard node-exporter port
