# ansible/roles/common/tasks/main.yml

- name: Include firewall setup tasks
  include_tasks: "roles/common/tasks/firewall.yml"

- name: Include containerd setup tasks
  include_tasks: "roles/common/tasks/containerd.yml"

- name: Include Docker setup tasks
  include_tasks: "roles/common/tasks/docker.yml"

- name: Include Kubernetes setup tasks
  include_tasks: "roles/common/tasks/kubernetes.yml"

- name: Disable swap and remove from /etc/fstab
  block:
    - name: Disable swap
      command: swapoff -a
      ignore_errors: yes

    - name: Remove swap from /etc/fstab
      ansible.builtin.lineinfile:
        path: /etc/fstab
        regexp: '^\s*\S+\s+none\s+swap\s+'
        line: "# Commented out by Ansible"
        state: absent

# - name: Ensure no conflicting Docker packages are installed
#   ansible.builtin.package:
#     name: "{{ item }}"
#     state: absent
#   loop:
#     - docker
#     - docker-engine
#     - docker.io
#     - runc

- name: Update and upgrade all packages
  ansible.builtin.apt:
    update_cache: yes
    upgrade: yes
    cache_valid_time: 3600

- name: Configure kernel modules and sysctl for Kubernetes
  block:
    - name: Load br_netfilter module
      ansible.builtin.modprobe:
        name: br_netfilter
        state: present

- name: Verify container runtime (containerd) is active and running
  ansible.builtin.systemd:
    name: containerd
    state: started
    enabled: yes

- name: Load necessary kernel modules
  ansible.builtin.modprobe:
    name: "{{ item }}"
    state: present
  loop:
    - overlay
    - br_netfilter

- name: Apply required sysctl settings for Kubernetes
  ansible.builtin.sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    state: present
    reload: yes
  loop:
    - { key: "net.bridge.bridge-nf-call-iptables", value: "1" }
    - { key: "net.bridge.bridge-nf-call-ip6tables", value: "1" }
    - { key: "net.ipv4.ip_forward", value: "1" }

- name: Verify net.bridge.bridge-nf-call-iptables is set to 1
  command: sysctl net.bridge.bridge-nf-call-iptables
  register: sysctl_check
  failed_when: "'net.bridge.bridge-nf-call-iptables = 1' not in sysctl_check.stdout"
