- name: Install Kubernetes tools
  include_tasks: kubernetes.yml

- name: Copy systemd service file for containerd
  ansible.builtin.template:
    src: "{{ playbook_dir }}/templates/containerd.service.j2"
    dest: /etc/systemd/system/containerd.service
  notify:
    - Reload systemd
    - Restart containerd
  become: true

- name: Initialize the Kubernetes cluster
  command: kubeadm init --pod-network-cidr=192.168.0.0/16
  register: kubeadm_init_output

- name: Save kubeadm init output as a fact
  ansible.builtin.set_fact:
    kubeadm_join_command: "{{ kubeadm_init_output.stdout_lines | select('match', '^kubeadm join.*$') | first }}"

- name: Create .kube directory
  file:
    path: "/home/ubuntu/.kube"
    state: directory
    owner: ubuntu
    group: ubuntu
    mode: '0755'

- name: Copy admin.conf to user's kube config
  copy:
    src: "/etc/kubernetes/admin.conf"
    dest: "/home/ubuntu/.kube/config"
    remote_src: yes
    owner: ubuntu
    group: ubuntu
    mode: '0644'

- name: Apply Calico network plugin
  command: kubectl apply -f https://docs.projectcalico.org/manifests/calico.yaml
  environment:
    KUBECONFIG: "/etc/kubernetes/admin.conf"
