#ansible/roles/master/tasks/main.yml
- name: Include common setup tasks
  include_tasks: "roles/common/tasks/main.yml"

- name: Copy systemd service file for containerd
  ansible.builtin.template:
    src: "roles/common/templates/containerd.service.j2"
    dest: /etc/systemd/system/containerd.service
  become: true


- name: Check if reboot is required
  stat:
    path: /var/run/reboot-required
  register: reboot_required

- name: Reboot the system if required
  ansible.builtin.reboot:
    msg: "Rebooting because of significant system changes"
    connect_timeout: 5
    reboot_timeout: 300
    pre_reboot_delay: 0
    post_reboot_delay: 60
    test_command: uptime
  when: reboot_required.stat.exists

# Part of master/tasks/main.yml

- name: Download kubectl
  ansible.builtin.get_url:
    url: https://dl.k8s.io/release/v1.28.8/bin/linux/amd64/kubectl
    dest: /tmp/kubectl
    mode: 0755

- name: Install kubectl
  ansible.builtin.copy:
    src: /tmp/kubectl
    dest: /usr/local/bin/kubectl
    remote_src: yes

- name: Download kubeadm
  ansible.builtin.get_url:
    url: https://dl.k8s.io/release/v1.28.8/bin/linux/amd64/kubeadm
    dest: /tmp/kubeadm
    mode: 0755

- name: Install kubeadm
  ansible.builtin.copy:
    src: /tmp/kubeadm
    dest: /usr/local/bin/kubeadm
    remote_src: yes

- name: Download kubelet
  ansible.builtin.get_url:
    url: https://dl.k8s.io/release/v1.28.8/bin/linux/amd64/kubelet
    dest: /tmp/kubelet
    mode: 0755

- name: Install kubelet
  ansible.builtin.copy:
    src: /tmp/kubelet
    dest: /usr/local/bin/kubelet
    remote_src: yes

