- name: Include common setup tasks
  include_tasks: "roles/common/tasks/main.yml"

- name: Copy systemd service file for containerd
  ansible.builtin.template:
    src: "roles/common/templates/containerd.service.j2"
    dest: /etc/systemd/system/containerd.service

  notify:
    - Reload systemd
    - Restart containerd
  become: true
  
- name: Install Kubernetes packages (kubeadm, kubelet, kubectl)
  ansible.builtin.apt:
    name:
      - kubeadm
      - kubelet
      - kubectl
    update_cache: yes
    state: present

- name: Initialize the Kubernetes cluster
  command: kubeadm init --pod-network-cidr=192.168.0.0/16
  register: kubeadm_init_output

- name: Save kubeadm init output as a fact
  ansible.builtin.set_fact:
    kubeadm_join_command: "{{ kubeadm_init_output.stdout_lines | select('match', '^kubeadm join.*$') | first }}"

- name: Create .kube directory
  file:
    path: "/home/ubuntu/.kube"
    state: directory
    owner: ubuntu
    group: ubuntu
    mode: '0755'

- name: Copy admin.conf to user's kube config
  copy:
    src: "/etc/kubernetes/admin.conf"
    dest: "/home/ubuntu/.kube/config"
    remote_src: yes
    owner: ubuntu
    group: ubuntu
    mode: '0644'

- name: Apply Calico network plugin
  command: kubectl apply -f https://docs.projectcalico.org/manifests/calico.yaml
  environment:
    KUBECONFIG: "/etc/kubernetes/admin.conf"


- name: Ensure Kubernetes packages are installed
  apt:
    name:
      - kubelet
      - kubeadm
      - kubectl
    state: present
    update_cache: yes

- name: Check kubeadm installation
  command: which kubeadm
  register: kubeadm_check
  failed_when: kubeadm_check.rc != 0

- name: Check kubelet installation
  command: which kubelet
  register: kubelet_check
  failed_when: kubelet_check.rc != 0

- name: Check kubectl installation
  command: which kubectl
  register: kubectl_check
  failed_when: kubectl_check.rc != 0

- name: Debug kubeadm installation check
  debug:
    msg: "kubeadm installed at: {{ kubeadm_check.stdout }}"
  when: kubeadm_check.rc == 0

- name: Debug kubelet installation check
  debug:
    msg: "kubelet installed at: {{ kubelet_check.stdout }}"
  when: kubelet_check.rc == 0

- name: Debug kubectl installation check
  debug:
    msg: "kubectl installed at: {{ kubectl_check.stdout }}"
  when: kubectl_check.rc == 0
