[master]
35.182.84.186 ansible_user=ubuntu ansible_ssh_private_key_file=./pro1.pem

[workers]
10.0.1.139 ansible_user=ubuntu ansible_ssh_private_key_file=./pro1.pem ansible_ssh_common_args='-o ProxyCommand="ssh -W %h:%p -q ubuntu@35.182.84.186 -i ./pro1.pem"'
10.0.2.66 ansible_user=ubuntu ansible_ssh_private_key_file=./pro1.pem ansible_ssh_common_args='-o ProxyCommand="ssh -W %h:%p -q ubuntu@35.182.84.186 -i ./pro1.pem"'
