[master]
15.157.72.208 ansible_user=ubuntu ansible_ssh_private_key_file=./pro1.pem

[workers]
10.0.1.88 ansible_user=ubuntu ansible_ssh_private_key_file=./pro1.pem ansible_ssh_common_args='-o ProxyCommand="ssh -W %h:%p -q ubuntu@15.157.72.208 -i ./pro1.pem"'
10.0.2.88 ansible_user=ubuntu ansible_ssh_private_key_file=./pro1.pem ansible_ssh_common_args='-o ProxyCommand="ssh -W %h:%p -q ubuntu@15.157.72.208 -i ./pro1.pem"'
