- hosts: all
  become: true
  roles:
    - common

- hosts: master
  become: true
  roles:
    - master
  tasks:
    - include_tasks: roles/master/tasks/kubernetes.yml

- hosts: workers
  become: true
  roles:
    - workers
  tasks:
    - include_tasks: roles/workers/tasks/kubernetes.yml


  tasks:
    - name: Update all packages
      ansible.builtin.apt:
        update_cache: yes
        upgrade: yes

    - name: Ensure no conflicting Docker packages are installed
      ansible.builtin.package:
        name: "{{ item }}"
        state: absent
      loop:
        - docker
        - docker-engine
        - docker.io
        - containerd
        - runc

    - name: Download and install containerd 1.7.14
      block:
        - name: Download containerd package
          ansible.builtin.get_url:
            url: "https://github.com/containerd/containerd/releases/download/v1.7.14/containerd-1.7.14-linux-amd64.tar.gz"
            dest: "/tmp/containerd-1.7.14-linux-amd64.tar.gz"
            mode: '0644'

        - name: Create containerd directory
          ansible.builtin.file:
            path: "/usr/local/bin"
            state: directory
            mode: '0755'

        - name: Extract containerd package
          ansible.builtin.unarchive:
            src: "/tmp/containerd-1.7.14-linux-amd64.tar.gz"
            dest: "/usr/local/bin"
            remote_src: yes
            extra_opts: ["--strip-components=1"]

        - name: Remove the downloaded tarball
          ansible.builtin.file:
            path: "/tmp/containerd-1.7.14-linux-amd64.tar.gz"
            state: absent
      become: true
      notify:
        - restart containerd

  handlers:
    - name: Restart containerd
      ansible.builtin.service:
        name: containerd
        state: restarted
        enabled: yes
        daemon_reload: yes

# Play for setting up the master node
- hosts: master
  become: true
  roles:
    - master

# Play for setting up worker nodes
- hosts: workers
  become: true
  roles:
    - workers







# - hosts: all
#   become: true
#   roles:
#     - common

# - hosts: master
#   become: true
#   roles:
#     - master
#   tasks:
#     - include_tasks: roles/master/tasks/kubernetes.yml

# - hosts: workers
#   become: true
#   roles:
#     - workers
#   tasks:
#     - include_tasks: roles/workers/tasks/kubernetes.yml

#   tasks:
#     - name: Update all packages
#       ansible.builtin.apt:
#         update_cache: yes
#         upgrade: yes

#     - name: Ensure no conflicting Docker packages are installed
#       ansible.builtin.package:
#         name: "{{ item }}"
#         state: absent
#       loop:
#         - docker
#         - docker-engine
#         - docker.io
#         - containerd
#         - runc

#     - name: Download and install containerd 1.7.14
#       block:
#         - name: Download containerd package
#           ansible.builtin.get_url:
#             url: "https://github.com/containerd/containerd/releases/download/v1.7.14/containerd-1.7.14-linux-amd64.tar.gz"
#             dest: "/tmp/containerd-1.7.14-linux-amd64.tar.gz"
#             mode: '0644'

#         - name: Create containerd directory
#           ansible.builtin.file:
#             path: "/usr/local/bin"
#             state: directory
#             mode: '0755'

#         - name: Extract containerd package
#           ansible.builtin.unarchive:
#             src: "/tmp/containerd-1.7.14-linux-amd64.tar.gz"
#             dest: "/usr/local/bin"
#             remote_src: yes
#             extra_opts: ["--strip-components=1"]

#         - name: Remove the downloaded tarball
#           ansible.builtin.file:
#             path: "/tmp/containerd-1.7.14-linux-amd64.tar.gz"
#             state: absent
#       become: true
#       notify:
#         - restart containerd

#   handlers:
#     - name: Restart containerd
#       ansible.builtin.service:
#         name: containerd
#         state: restarted
#         enabled: yes
#         daemon_reload: yes

# - hosts: master
#   become: true
#   roles:
#     - master
#   tasks:
#     - include_tasks: roles/master/tasks/kubernetes.yml

# - hosts: workers
#   become: true
#   roles:
#     - workers
#   tasks:
#     - include_tasks: roles/workers/tasks/kubernetes.yml





